# Generated by Django 5.2.10 on 2026-01-30 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Остаток на складе')),
                ('min_quantity', models.IntegerField(default=0, verbose_name='Минимальный остаток')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Складской остаток',
                'verbose_name_plural': 'Складские остатки',
            },
        ),
    ]
