# Generated by Django 5.2.10 on 2026-01-30 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0009_alter_order_external_id_alter_supplyitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('marketplace', models.CharField(db_index=True, default='kaspi', max_length=32)),
                ('order_id', models.CharField(db_index=True, max_length=64)),
                ('sku', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(max_length=512)),
                ('category', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('qty', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='orders.product')),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='analytics_s_date_d33567_idx'), models.Index(fields=['product'], name='analytics_s_product_18c682_idx'), models.Index(fields=['sku'], name='analytics_s_sku_cb7038_idx'), models.Index(fields=['category'], name='analytics_s_categor_fc456e_idx')],
                'unique_together': {('order_id', 'sku')},
            },
        ),
    ]
