# Generated by Django 5.2.10 on 2026-01-30 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0007_delete_orderfinancesnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFinanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('marketplace_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('factoring_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance', to='orders.order')),
            ],
        ),
    ]
