# Generated by Django 5.2.10 on 2026-01-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_integrationsyncstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=64, unique=True)),
                ('backfill_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
