# Generated by Django 5.2.10 on 2026-01-31 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_integrationstate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntegrationState',
        ),
    ]
