# Generated by Django 5.2.10 on 2026-01-30 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0009_alter_order_external_id_alter_supplyitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='orders.supplier', verbose_name='Поставщик'),
        ),
    ]
