# Generated by Django 6.0.1 on 2026-01-29 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('source', models.CharField(choices=[('kaspi', 'Kaspi'), ('ozon', 'Ozon'), ('wb', 'Wildberries')], max_length=16)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(db_index=True, max_length=64)),
                ('state', models.CharField(db_index=True, max_length=64)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_mode', models.CharField(blank=True, max_length=64, null=True)),
                ('delivery_mode', models.CharField(blank=True, max_length=64, null=True)),
                ('is_express', models.BooleanField(default=False)),
                ('is_preorder', models.BooleanField(default=False)),
                ('signature_required', models.BooleanField(default=False)),
                ('created_at_source', models.DateTimeField()),
                ('approved_at_source', models.DateTimeField(blank=True, null=True)),
                ('planned_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliverySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('pickup_point', models.CharField(blank=True, max_length=128, null=True)),
                ('raw_data', models.JSONField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(max_length=64)),
                ('raw_data', models.JSONField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=64)),
                ('sku', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(max_length=512)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(blank=True, max_length=256, null=True)),
                ('raw_data', models.JSONField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
                ('changed_at', models.DateTimeField()),
                ('raw_data', models.JSONField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
