# Generated by Django 5.2.10 on 2026-01-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='state',
            new_name='marketplace_state',
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='marketplace_status',
            field=models.CharField(db_index=True, default='legacy', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='source',
            field=models.CharField(default='legacy', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('approved', 'Подтверждён'), ('packing', 'Сборка'), ('shipped', 'Отгружен'), ('in_transit', 'В пути'), ('delivered', 'Доставлен'), ('completed', 'Завершён'), ('cancelled', 'Отменён'), ('returned', 'Возврат')], db_index=True, default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('approved', 'Подтверждён'), ('packing', 'Сборка'), ('shipped', 'Отгружен'), ('in_transit', 'В пути'), ('delivered', 'Доставлен'), ('completed', 'Завершён'), ('cancelled', 'Отменён'), ('returned', 'Возврат')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['source', 'external_id'], name='orders_orde_source_f73479_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at_source'], name='orders_orde_created_153353_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['sku'], name='orders_orde_sku_737ca0_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['external_id'], name='orders_orde_externa_953e62_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['status'], name='orders_orde_status_3c2037_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['changed_at'], name='orders_orde_changed_14af81_idx'),
        ),
    ]
