# Generated by Django 5.2.10 on 2026-01-30 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_state_order_marketplace_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Закупочная цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='marketplace_state',
            field=models.CharField(db_index=True, default='unknown', max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='marketplace_status',
            field=models.CharField(db_index=True, default='unknown', max_length=64),
        ),
        migrations.CreateModel(
            name='OrderFinanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Закупка')),
                ('marketplace_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Комиссия маркетплейса')),
                ('factoring_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Факторинг')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Доставка')),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Валовая прибыль')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Чистая прибыль')),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Маржа %')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance', to='orders.order')),
            ],
        ),
    ]
