# Generated by Django 5.2.10 on 2026-01-30 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_product_supplier_supplyorder_supplyitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyorder',
            name='is_stock_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FinanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('in', 'Поступление'), ('out', 'Выплата')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('planned_at', models.DateTimeField()),
                ('actual_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
            ],
        ),
    ]
