# Generated by Django 5.2.10 on 2026-01-30 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_supplyorder_is_stock_applied_financeevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at_source',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
