# Generated by Django 5.2.10 on 2026-01-30 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_created_at_source'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderFinanceSnapshot',
        ),
    ]
