# Generated by Django 5.2.10 on 2026-01-30 19:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0008_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='external_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='supplyitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_items', to='catalog.product', verbose_name='Товар'),
        ),
    ]
