# Generated by Django 5.2.10 on 2026-02-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orderitem_name_alter_orderitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='kaspi_category',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Категория Kaspi'),
        ),
        migrations.AddField(
            model_name='product',
            name='kaspi_enabled',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Выгружать в Kaspi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена продажи'),
        ),
    ]
